
SET ANSI_NULLS ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

declare @cNumero varchar(9)
set @cNumero ='6874'


declare @NUM_TIT_PG varchar(9)
declare @SALD_TIT_PG varchar(20)
declare @VAL_TIT_PG varchar(20)
declare @VALOR_TOTAL varchar(9)
declare @SOMA_SALDO varchar(20)
declare @QUANT_CIF varchar(20)



SELECT DISTINCT
(SELECT TOP 1 E2_XDECOMP FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS E2_XDECOMPSE2 ,
(SELECT TOP 1  SUM(E2_VALOR) AS SOMA_VALLQ FROM SE2010(NOLOCK) WHERE 0=0 AND E2_TIPO ='CIF' AND D_E_L_E_T_ ='') as VALOR_TOTAL,
(SELECT TOP 1  SUM(E2_SALDO)  AS SOMA_SALDO FROM SE2010(NOLOCK) WHERE 0=0 AND E2_TIPO ='CIF' AND D_E_L_E_T_ ='') AS SOMA_SALDO,
(SELECT TOP 1  COUNT(E2_NUM)  AS QUANT_CIF FROM SE2010(NOLOCK) WHERE 0=0 AND E2_TIPO ='CIF' AND D_E_L_E_T_ ='') AS QUANT_CIF,
(SELECT TOP 1  CAST(E2_EMISSAO AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS DTEMISS_TIT_PG ,
(SELECT TOP 1  CAST(E2_VENCTO  AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VENC_TIT_PG,
(SELECT TOP 1  CAST(E2_VENCORI AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VENORI_TIT_PG,
(SELECT TOP 1  CAST(E2_VENCREA AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VENREAL_TIT_PG,
(SELECT TOP 1  CAST(E5_DTDIGIT AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS CONTBFIN_TIT_PG,
(SELECT TOP 1  CAST(E2_DATALIB AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS DTLIB_TIT_PG,
(SELECT DISTINCT E2_NUM FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS NUM_TIT_PG ,
(SELECT DISTINCT E2_VALOR FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VAL_TIT_PG,
(SELECT DISTINCT E2_SALDO FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS SALD_TIT_PG,
(SELECT TOP 1  E2_VALLIQ FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VALLIQ_TIT_PG,
	E2_FILIAL,
	E2_XDECOMP,
	E2_NATUREZ,
	E2_PREFIXO,
	E2_NUM,
	FK7_NUM,
	E5_NUMERO,
	E5_NUMMOV,
	E2_PARCELA,
	E2_TIPO,
	E2_NATUREZ,
	E2_MOEDA,
	E2_FORNECE,
	E2_LOJA,
	E2_NOMFOR,
	CAST(E2_HIST AS VARCHAR (35)) E2_HIST,
	E2_VALOR,
	E2_VLCRUZ,
	E2_TXMOEDA,
	E2_SDACRES,
	E2_SDDECRE,
	 CAST(E2_EMISSAO AS DATE) E2_EMISSAO,
	 CAST(E2_VENCTO  AS DATE) E2_VENCTO,
	 CAST(E2_VENCREA AS DATE) E2_VENCREA,
	 CAST(E2_VENCORI AS DATE) E2_VENCORI,
	 CAST(E2_VENCREA AS DATE) E2_VENCREA,
	 CAST(E2_VENCISS AS DATE) E2_VENCISS,
	 CAST(E2_CONTAB  AS DATE) E2_CONTAB,
	 CAST(E2_DATALIB AS DATE) E2_DATALIB,
	E2_SALDO,
	E2_LOTE,
	E2_STATLIB,
	E2_STATUS,
-------------------
	E5_TIPO,
	E5_FILIAL,
	E5_PREFIXO,
	E5_NUMERO,
	E5_PARCELA,
	E5_TIPO,
	E5_FORNECE,
	E5_LOJA,
	E5_MOTBX,
	CAST(E5_DATA AS DATE) E5_DATA,
	CAST(E5_DTDIGIT AS DATE) E5_DTDIGIT,
	CAST(E5_DTCANBX AS DATE) E5_DTCANBX,
	CAST(E5_DTDISPO AS DATE) E5_DTDISPO,
	E5_IDORIG,
	E5_VLJUROS,
	E5_VLMULTA,
	E5_VALOR,
	E5_VLCORRE,
	E5_VLDESCO,
	E5_TIPODOC,
	E5_RECONC,
	E5_DOCUMEN,
	E5_HISTOR,
	E5_LOTE,
	E5_BANCO,
	E5_AGENCIA,
	E5_CONTA,
	E5_NUMCHEQ,
	E5_NATUREZ,
	E5_NUMMOV,
	FK2_IDDOC,
	FK2_IDCOMP AS COMPENSACAO,
	FK7_IDDOC,
	FK2_IDFK2,
	E5_IDORIG,
	FK7_NUM,
	FK7_CHAVE
	--------


FROM SE2010   SE2 WITH(NOLOCK)
	INNER JOIN SE5010 SE5 WITH(NOLOCK)
		ON (E2_FILIAL+E2_PREFIXO+E2_NUM+E2_PARCELA+E2_FORNECE+E2_LOJA)  
		=  (E5_FILIAL+E5_PREFIXO+E5_NUMERO+E5_PARCELA+E5_FORNECE+E5_LOJA)
		
		INNER JOIN FK2010 FK2 WITH (NOLOCK)
			ON E5_IDORIG = FK2.FK2_IDFK2

			INNER JOIN FK7010 FK7 WITH (NOLOCK)
				ON FK2.FK2_IDCOMP = FK7_IDDOC

 	
WHERE 0=0
        AND SE2.D_E_L_E_T_ =''
        AND SE5.D_E_L_E_T_ =''
	    AND E5_CLIFOR ='UNIAO'
		AND E2_TIPO   <> 'CIF'
	   -- AND E2_NUM like  '%'+@cNumero+'%'
	    and E2_NUM = @cNumero
		 and E2_NUM = E5_NUMERO
		--OR  FK7_CHAVE LIKE '%'+@cNumero+'%'


UNION 

SELECT DISTINCT
(SELECT TOP 1 E2_XDECOMP FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS E2_XDECOMPSE2 ,
(SELECT TOP 1  SUM(E2_VALOR) AS SOMA_VALLQ FROM SE2010(NOLOCK) WHERE 0=0 AND E2_TIPO ='CIF' AND D_E_L_E_T_ ='') as VALOR_TOTAL,
(SELECT TOP 1  SUM(E2_SALDO)  AS SOMA_SALDO FROM SE2010(NOLOCK) WHERE 0=0 AND E2_TIPO ='CIF' AND D_E_L_E_T_ ='') AS SOMA_SALDO,
(SELECT TOP 1  COUNT(E2_NUM)  AS QUANT_CIF FROM SE2010(NOLOCK) WHERE 0=0 AND E2_TIPO ='CIF' AND D_E_L_E_T_ ='') AS QUANT_CIF,
(SELECT TOP 1  CAST(E2_EMISSAO AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS DTEMISS_TIT_PG ,
(SELECT TOP 1  CAST(E2_VENCTO  AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VENC_TIT_PG,
(SELECT TOP 1  CAST(E2_VENCORI AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VENORI_TIT_PG,
(SELECT TOP 1  CAST(E2_VENCREA AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VENREAL_TIT_PG,
(SELECT TOP 1  CAST(E5_DTDIGIT AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS CONTBFIN_TIT_PG,
(SELECT TOP 1  CAST(E2_DATALIB AS DATE)FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS DTLIB_TIT_PG,
(SELECT DISTINCT E2_NUM FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS NUM_TIT_PG ,
(SELECT DISTINCT E2_VALOR FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VAL_TIT_PG,
(SELECT DISTINCT E2_SALDO FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS SALD_TIT_PG,
(SELECT TOP 1  E2_VALLIQ FROM SE2010 SE2 INNER JOIN SE5010 SE5 ON (E2_FILIAL = E5_FILIAL AND E2_NUM=E5_NUMERO ) WHERE SE2.D_E_L_E_T_ = '' AND SE5.D_E_L_E_T_ = '' AND( E2_NUM = @cNumero)) AS VALLIQ_TIT_PG,
	E2_FILIAL,
	E2_XDECOMP,
	E2_NATUREZ,
	E2_PREFIXO,
	E2_NUM,
	FK7_NUM,
	E5_NUMERO,
	E5_NUMMOV,
	E2_PARCELA,
	E2_TIPO,
	E2_NATUREZ,
	E2_MOEDA,
	E2_FORNECE,
	E2_LOJA,
	E2_NOMFOR,
	CAST(E2_HIST AS VARCHAR (35)) E2_HIST,
	E2_VALOR,
	E2_VLCRUZ,
	E2_TXMOEDA,
	E2_SDACRES,
	E2_SDDECRE,
	 CAST(E2_EMISSAO AS DATE) E2_EMISSAO,
	 CAST(E2_VENCTO  AS DATE) E2_VENCTO,
	 CAST(E2_VENCREA AS DATE) E2_VENCREA,
	 CAST(E2_VENCORI AS DATE) E2_VENCORI,
	 CAST(E2_VENCREA AS DATE) E2_VENCREA,
	 CAST(E2_VENCISS AS DATE) E2_VENCISS,
	 CAST(E2_CONTAB  AS DATE) E2_CONTAB,
	 CAST(E2_DATALIB AS DATE) E2_DATALIB,
	E2_SALDO,
	E2_LOTE,
	E2_STATLIB,
	E2_STATUS,
-------------------
	E5_TIPO,
	E5_FILIAL,
	E5_PREFIXO,
	E5_NUMERO,
	E5_PARCELA,
	E5_TIPO,
	E5_FORNECE,
	E5_LOJA,
	E5_MOTBX,
	CAST(E5_DATA AS DATE) E5_DATA,
	CAST(E5_DTDIGIT AS DATE) E5_DTDIGIT,
	CAST(E5_DTCANBX AS DATE) E5_DTCANBX,
	CAST(E5_DTDISPO AS DATE) E5_DTDISPO,
	E5_IDORIG,
	E5_VLJUROS,
	E5_VALOR,
	E5_VLMULTA,
	E5_VLCORRE,
	E5_VLDESCO,
	E5_TIPODOC,
	E5_RECONC,
	E5_DOCUMEN,
	E5_HISTOR,
	E5_LOTE,
	E5_BANCO,
	E5_AGENCIA,
	E5_CONTA,
	E5_NUMCHEQ,
	E5_NATUREZ,
	E5_NUMMOV,
	FK2_IDDOC,
	FK2_IDCOMP AS COMPENSACAO,
	FK7_IDDOC,
	FK2_IDFK2,
	E5_IDORIG,
	FK7_NUM,
	FK7_CHAVE

FROM SE2010   SE2 WITH(NOLOCK)
	INNER JOIN SE5010 SE5 WITH(NOLOCK)
		ON (E2_FILIAL+E2_PREFIXO+E2_LOJA)  
		=  (E5_FILIAL+E5_PREFIXO+E5_LOJA)
		
		INNER JOIN FK2010 FK2 WITH (NOLOCK)
			ON E5_IDORIG = FK2.FK2_IDFK2

			INNER JOIN FK7010 FK7 WITH (NOLOCK)
				ON FK2.FK2_IDCOMP = FK7_IDDOC


WHERE 0=0
        AND SE2.D_E_L_E_T_ =''
        AND SE5.D_E_L_E_T_ =''
	    AND E5_CLIFOR ='UNIAO'
		AND E2_TIPO <> 'CIF'
	    and FK2.FK2_IDCOMP = FK7_IDDOC
		AND E2_NUM =  FK7_NUM
		AND E5_NUMERO = @cNumero